\input texinfo  @c -*-texinfo-*-
@c %**start of header
@setfilename jwhois.info
@settitle jwhois, Whois client
@c %**end of header

@c This file has the new style title page commands.
@c Run `makeinfo' rather than `texinfo-format-buffer'.

@c smallbook

@c tex
@c \overfullrule=0pt
@c end tex

@c Combine indices.
@synindex cp fn
@syncodeindex vr fn
@syncodeindex ky fn
@syncodeindex pg fn
@syncodeindex tp fn

@ifinfo
This file documents @sc{jwhois}, a Whois client.

Copyright (C) 1999 Jonas Öberg

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

@ignore
Permission is granted to process this file through TeX and print the
results, provided the printed document carries copying permission
notice identical to this one except for the removal of this paragraph
(this paragraph not being relevant to the printed manual).

@end ignore
Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.
@end ifinfo

@setchapternewpage off

@titlepage
@title jwhois, Whoisclient

@author by Jonas Öberg
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 1999 Jonas Öberg

@sp 2
Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.
@end titlepage
@page

@node Top, Introduction, (dir), (dir)

@menu
* Introduction::                Introduction
* Invocation::                  How to invoke jwhois
* RIPE Extensions::             Extensions for RIPE databases
* Site Configuration::          Defining a list of Whois servers
* Reporting bugs::              Reporting bugs
@end menu

@node Introduction, Invocation, Top, Top
@comment  node-name,  next,  previous,  up
@chapter Introduction

@sc{jwhois} is an Internet Whois client that queries hosts for information
according to RFC 954 - NICNAME/WHOIS. @sc{jwhois} can be configured to
decide via regular expressions which servers to query for information, based
on the information that the user wishes to retrieve.

@node Invocation, RIPE Extensions, Introduction, Top
@chapter Invocation

@sc{jwhois} uses the following command-line options:
@table @samp

@item --version
Print the version information for this program, then exit.

@item --help
Print a usage message summarizing the command-line options, then exit.

@item -c FILE
@item --config=FILE
Reads configuration from FILE instead of the default.

@item -h HOST
@item --host=HOST
Overrides any specifications in the configuration file and queries HOST
directly.

@item -p PORT
@item --port=PORT
Specifies a port number to use when querying a HOST

@end table

@node RIPE Extensions, Site Configuration, Invocation, Top
@chapter RIPE Extensions

RIPE (Réseaux IP Européens) has defined a number of options that can be
used against a RIPE-compatible whois server (ripe.net, apnic.net and
others).  Unfortunately, there is really no way of telling whether a
host we are connecting to is RIPE-compatible or not.  RIPE extensions
are therefor not directly incorporated into the @sc{jwhois} client.
A list of the options can be found in RIPE Document 157 which you can get
from the RIPE ftp server, @url{ftp://ftp.ripe.net/ripe/docs/}.

It is possible to use these options together with @sc{jwhois} by changing
the format of the query slightly. If you were to search for all entries in
the RIPE database which lists the admin-c, tech-c or zone-c as CO19-RIPE,
you could use the following command syntax:

@example
$ jwhois -h whois.ripe.net -- "-i admin-c,tech-c,zone-c CO19-RIPE"
@end example

@samp{--} is used to separate the RIPE options from the jwhois options.

@node Site Configuration, Reporting bugs, RIPE Extensions, Top
@chapter Site Configuration

@sc{jwhois} is configurable via its @file{jwhois.conf} file. This file
is looked for in the sysconfdir that was specified when compiling the
program (default is @file{/usr/local/etc/}). If this file can not be
found, it will look for it in datadir (default is @file{/usr/local/share}).
If no configuration file can be found, @sc{jwhois} will default all queries
to @url{whois.internic.net} or the DEFAULTHOST that was specified when
compiling the program.

An example configuration file that includes most known Whois servers can be
found in the @code{example} subdirectory of the official distribution.

The configuration file is split into a number of blocks. Each block
can be associated with a type, either @samp{cidr} or @samp{regex}.
@sc{jwhois} will first look for matches in the @samp{whois-servers} block
and follow the instructions given.

All blocks consists of a number of key and value pairs.

The value of each pair can be either a host name, optionally postfixed
with with an alternative port number (separated from the host name or
IP number by a single space), or the special token @samp{struct} which
redirects the query to another block.

The special key token @samp{type} defines the type for the given block.

@node Reporting bugs,  , Site Configuration, Top
@chapter Reporting bugs

Email bug reports to @code{jonas@@coyote.org}.

@contents
@bye
