.PU
.TH jwhois 1 local
.SH NAME
jwhois \- client for the whois service
.SH SYNOPSIS
.ll +8
.B whois
.RB
[
.I "OPTIONS"
]...
[
.I "QUERY"
]
.ll -8
.SH DESCRIPTION
.I jwhois
searches Whois servers for the object on the command line.

The host to query is taken from a global configuration file,
a configuration file specified on the command line, or selected
directly on the command line.

.SH OPTIONS
.TP
.B \--version
display version, authors and licensing information
.TP
.B \--help
display a short help text
.TP
.B \-c FILE --config=FILE
uses FILE as a configuration file instead of the default
.TP
.B \-h HOST --host=HOST
overrides any hosts in the configuration file and queries HOST directly
.TP
.B \-p PORT --port=PORT
specifies a port number to use when querying a HOST
.TP
.B \-v --verbose
outputs verbose debugging information while running
.TP
.B \-n --no-redirect
disable content redirection
.TP
.B \-f --force-lookup
forces a query to be made to a host even if the object is stored in cache
.TP
.B \-d --disable-cache
completely disable both reading and writing to cache

.SS "RIPE EXTENSIONS"
To use the options specified in
.IR "RIPE Document 157" ,
you need to change the format of thre query slightly.
If you were to search for all entries in
the RIPE database which lists the
.IR admin-c ", " tech-c " or " zone-c " as " CO19-RIPE ,
you could use the following command syntax:

.B jwhois -h whois.ripe.net -- \-i admin-c,tech-c,zone-c CO19-RIPE

.B --
is used to separate the RIPE options from the jwhois options.

.ll -8
.SH "SEE ALSO"
whois(1)
