#!/bin/sh -e

#DEBHELPER#

# Breakage: <= 2.4.1 used jwhois.db.db, 2.4.2+ use jwhois.db
# Breakage: 2.4.2-1 did not recognize this (so if we're upgrading
# from it, we might get doubled caches)

if test "$1" = "configure"; then
  if dpkg --compare-versions "$2" le "2.4.2-1"; then
    # If old cache exists, and new does not, move it
    if test -e /var/cache/jwhois/jwhois.db.db -a ! -e /var/cache/jwhois/jwhois.db; then
      mv -f /var/cache/jwhois/jwhois.db.db /var/cache/jwhois/jwhois.db
    fi
    # Remove possible left-over old cache
    rm -f /var/cache/jwhois/jwhois.db.db
  fi
fi

# Add the group 'jwhois' that the cache uses

if getent group jwhois > /dev/null; then
  # Group already exists
  true
else
  # Group did not exist
  addgroup --system jwhois || true
fi

# Setgid binary to the jwhois group if no statoverride was set

jwhoisoverride=`dpkg-statoverride --list /usr/bin/jwhois`
if test "$jwhoisoverride" = ""; then
  if getent group jwhois > /dev/null; then
    if chown root.jwhois /usr/bin/jwhois; then
      chmod 02755 /usr/bin/jwhois || echo "Failed setting jwhois permissions, cache functionality may be impaired."
    else
      echo "Failed setting jwhois ownership, cache functionality may be impaired."
    fi
  else
    echo "Jwhois group is missing, cache functionality will be impaired."
  fi
fi

# Setgid cache directory to the jwhois group, and add it to
# dpkg-statoverride unless it's already overridden.

cacheoverride=`dpkg-statoverride --list /var/cache/jwhois`
if test "$cacheoverride" = ""; then
  if getent group jwhois > /dev/null; then
    if chown root.jwhois /var/cache/jwhois; then
      chmod 0775 /var/cache/jwhois || echo "Failed setting cache directory permissions, cache functionality may be impaired."
    else
      echo "Failed setting cache directory ownership, cache functionality may be impaired."
    fi

    # Make sure the cache, if it exists, has the correct group ownership

    if test -e /var/cache/jwhois/jwhois.db; then
      chgrp jwhois /var/cache/jwhois/jwhois.db || echo "Failed setting cache file ownership, cache functionality may be impaired."
    fi
  else
    echo " Jwhois group is missing, not setting ownership of cache directory."
  fi
fi
